spring.application.name=questapp

spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/quest-app}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


questapp.app.secret=${JWT_SECRET}
questapp.expires.in=${JWT_EXPIRES_IN:604800}

logging.level.org.springframework.security=DEBUG
logging.level.com.example.questapp=DEBUG
